spring.application.name=fraud-detection

# kafak
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.topic=fraud-detection-topic
spring.kafka.listener.ack-mode=manual
spring.kafka.consumer.group-id=fraud-detection-group
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.threadPool.num=2

# ????
spring.datasource.url=jdbc:h2:mem:fraud_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=fraud
spring.datasource.password=fraud
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.sql.init.schema-locations=classpath:schema.sql
spring.h2.console.settings.web-allow-others=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# ????
spring.fraud.detect.rules.max-amount=100000
spring.fraud.detect.rules.user-id.blacklist=123,456
spring.fraud.detect.demotion.switch=false

# ??????
spring.fraud.detect.sendAlert.threadPool.num=2
spring.mail.smtp.host=smtp.qq.com
spring.mail.fromAccount=sventao@qq.com
spring.mail.toAccount=sventao@qq.com

# awsCloudWatch
spring.awsCloudWatch.log.region=awsCloudWatchLogRegion
spring.awsCloudWatch.log.group=awsCloudWatchLogGroup
spring.awsCloudWatch.log.stream=awsCloudWatchLogStream